In [22]:
import yfinance as yf

appl = yf.Ticker("AAPL")

In [64]:
appl

yfinance.Ticker object <AAPL>

In [23]:
# get all stock info
appl.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '408 996 1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 161000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 62,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'totalPay': 16239562,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Luca  Maestri',
   'age': 60,
   'title': 'CFO & Senior VP',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 4612242,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 59,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4637585,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 59,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4618064,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 56,
   'title': 'Senior Vice President of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 4613369,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James  Wilson',
   'title': 'Chief Technology Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 49,
   'title': 'Head of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 4,
 'boardRisk': 1,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1706745600,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 189.41,
 'open': 189.385,
 'dayLow': 187.35,
 'dayHigh': 189.535,
 'regularMarketPreviousClose': 189.41,
 'regularMarketOpen': 189.385,
 'regularMarketDayLow': 187.35,
 'regularMarketDayHigh': 189.535,
 'dividendRate': 0.96,
 'dividendYield': 0.0050999997,
 'exDividendDate': 1707436800,
 'payoutRatio': 0.14770001,
 'fiveYearAvgDividendYield': 0.78,
 'beta': 1.312,
 'trailingPE': 29.517242,
 'forwardPE': 26.301678,
 'volume': 39248768,
 'regularMarketVolume': 39248768,
 'averageVolume': 53867895,
 'averageVolume10days': 59189090,
 'averageDailyVolume10Day': 59189090,
 'bid': 188.16,
 'ask': 188.2,
 'bidSize': 1000,
 'askSize': 1400,
 'marketCap': 2908018704384,
 'fiftyTwoWeekLow': 143.9,
 'fiftyTwoWeekHigh': 199.62,
 'priceToSalesTrailing12Months': 7.5394697,
 'fiftyDayAverage': 190.5398,
 'twoHundredDayAverage': 182.82735,
 'trailingAnnualDividendRate': 0.95,
 'trailingAnnualDividendYield': 0.0050155744,
 'currency': 'USD',
 'enterpriseValue': 2942955159552,
 'profitMargins': 0.26163,
 'floatShares': 15414240033,
 'sharesOutstanding': 15441899520,
 'sharesShort': 101263039,
 'sharesShortPriorMonth': 120233720,
 'sharesShortPreviousMonthDate': 1702598400,
 'dateShortInterest': 1705017600,
 'sharesPercentSharesOut': 0.0064999997,
 'heldPercentInsiders': 0.06002,
 'heldPercentInstitutions': 0.56006,
 'shortRatio': 1.83,
 'shortPercentOfFloat': 0.0066000004,
 'impliedSharesOutstanding': 15770500096,
 'bookValue': 4.793,
 'priceToBook': 39.29063,
 'lastFiscalYearEnd': 1696032000,
 'nextFiscalYearEnd': 1727654400,
 'mostRecentQuarter': 1703894400,
 'earningsQuarterlyGrowth': 0.131,
 'netIncomeToCommon': 100912996352,
 'trailingEps': 6.38,
 'forwardEps': 7.16,
 'pegRatio': 2.62,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 7.63,
 'enterpriseToEbitda': 22.619,
 '52WeekChange': 0.25428784,
 'SandP52WeekChange': 0.22114873,
 'lastDividendValue': 0.24,
 'lastDividendDate': 1699574400,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'AAPL',
 'underlyingSymbol': 'AAPL',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'firstTradeDateEpochUtc': 345479400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa',
 'messageBoardId': 'finmb_24937',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 188.32,
 'targetHighPrice': 250.0,
 'targetLowPrice': 158.0,
 'targetMeanPrice': 201.08,
 'targetMedianPrice': 200.0,
 'recommendationMean': 2.1,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 73100001280,
 'totalCashPerShare': 4.734,
 'ebitda': 130108997632,
 'totalDebt': 108040003584,
 'quickRatio': 0.92,
 'currentRatio': 1.073,
 'totalRevenue': 385706000384,
 'debtToEquity': 145.803,
 'revenuePerShare': 24.648,
 'returnOnAssets': 0.21181,
 'returnOnEquity': 1.5426899,
 'freeCashflow': 86563127296,
 'operatingCashflow': 116433002496,
 'earningsGrowth': 0.16,
 'revenueGrowth': 0.021,
 'grossMargins': 0.45027,
 'ebitdaMargins': 0.33733,
 'operatingMargins': 0.33764,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.3172}

In [24]:
appl.info['financialCurrency']

'USD'

In [25]:
# get historical market data
hist = appl.history(period="1mo")

In [26]:
# show meta information about the history (requires history() to be called first)
appl.history_metadata

{'currency': 'USD',
 'symbol': 'AAPL',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 345479400,
 'regularMarketTime': 1707426001,
 'gmtoffset': -18000,
 'timezone': 'EST',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 188.32,
 'chartPreviousClose': 185.56,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EST',
   'start': 1707382800,
   'end': 1707402600,
   'gmtoffset': -18000},
  'regular': {'timezone': 'EST',
   'start': 1707402600,
   'end': 1707426000,
   'gmtoffset': -18000},
  'post': {'timezone': 'EST',
   'start': 1707426000,
   'end': 1707440400,
   'gmtoffset': -18000}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [27]:
# show actions (dividends, splits, capital gains)
appl.actions
appl.dividends
appl.splits
appl.capital_gains

Series([], dtype: object)

In [28]:
# show share count
appl.get_shares_full(start="2022-01-01", end=None)

2022-01-10 00:00:00-05:00    16334399488
2022-01-31 00:00:00-05:00    16319399936
2022-02-04 00:00:00-05:00    16319399936
2022-02-05 00:00:00-05:00    16319399936
2022-02-11 00:00:00-05:00    16319399936
                                ...
2024-01-16 00:00:00-05:00    15462700032
2024-01-16 00:00:00-05:00    15461900288
2024-02-01 00:00:00-05:00    15461900288
2024-02-01 00:00:00-05:00    15770500096
2024-02-03 00:00:00-05:00    15441899520
Length: 101, dtype: int64

In [77]:
# show financials:
# - income statement\n
appl.income_stmt
appl.quarterly_income_stmt

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.159,0.149715,0.125,0.149,0.158
Normalized EBITDA,43221000000.0,30653000000.0,26783000000.0,32210000000.0,38932000000.0
Net Income From Continuing Operation Net Minority Interest,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Reconciled Depreciation,2848000000.0,2653000000.0,3052000000.0,2898000000.0,2916000000.0
Reconciled Cost Of Revenue,64720000000.0,49071000000.0,45384000000.0,52860000000.0,66822000000.0
EBITDA,43221000000.0,30653000000.0,26783000000.0,32210000000.0,38932000000.0
EBIT,40373000000.0,28000000000.0,23731000000.0,29312000000.0,36016000000.0
Net Interest Income,NaN,-18000000.0,-18000000.0,-12000000.0,-135000000.0
Interest Expense,NaN,1002000000.0,998000000.0,930000000.0,1003000000.0
Interest Income,NaN,984000000.0,980000000.0,918000000.0,868000000.0
Normalized Income,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income From Continuing And Discontinued Operation,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Total Expenses,79202000000.0,62529000000.0,58799000000.0,66518000000.0,81138000000.0
Total Operating Income As Reported,40373000000.0,26969000000.0,22998000000.0,28318000000.0,36016000000.0
Diluted Average Shares,15576641000.0,15672400000.0,15775021000.0,15847050000.0,15955718000.0
Basic Average Shares,15509763000.0,15599434000.0,15697614000.0,15787154000.0,15892723000.0
Diluted EPS,2.18,1.46,1.26,1.52,1.88
Basic EPS,2.19,1.47,1.27,1.53,1.89
Diluted NI Availto Com Stockholders,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Common Stockholders,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Including Noncontrolling Interests,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Continuous Operations,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Tax Provision,6407000000.0,4042000000.0,2852000000.0,4222000000.0,5625000000.0
Pretax Income,40323000000.0,26998000000.0,22733000000.0,28382000000.0,35623000000.0
Other Income Expense,-50000000.0,47000000.0,-247000000.0,76000000.0,-393000000.0
Other Non Operating Income Expenses,-50000000.0,47000000.0,-247000000.0,76000000.0,-393000000.0
Net Non Operating Interest Income Expense,NaN,-18000000.0,-18000000.0,-12000000.0,-135000000.0
Interest Expense Non Operating,NaN,1002000000.0,998000000.0,930000000.0,1003000000.0
Interest Income Non Operating,NaN,984000000.0,980000000.0,918000000.0,868000000.0
Operating Income,40373000000.0,26969000000.0,22998000000.0,28318000000.0,36016000000.0
Operating Expense,14482000000.0,13458000000.0,13415000000.0,13658000000.0,14316000000.0
Research And Development,7696000000.0,7307000000.0,7442000000.0,7457000000.0,7709000000.0
Selling General And Administration,6786000000.0,6151000000.0,5973000000.0,6201000000.0,6607000000.0
Gross Profit,54855000000.0,40427000000.0,36413000000.0,41976000000.0,50332000000.0
Cost Of Revenue,64720000000.0,49071000000.0,45384000000.0,52860000000.0,66822000000.0
Total Revenue,119575000000.0,89498000000.0,81797000000.0,94836000000.0,117154000000.0
Operating Revenue,119575000000.0,89498000000.0,81797000000.0,94836000000.0,117154000000.0

In [38]:
# - balance sheet
appl.balance_sheet
appl.quarterly_balance_sheet

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Treasury Shares Number,0.0,0.0,NaN,NaN,NaN
Ordinary Shares Number,15460223000.0,15550061000.0,15647868000.0,15723406000.0,15842407000.0
Share Issued,15460223000.0,15550061000.0,15647868000.0,15723406000.0,15842407000.0
Net Debt,67280000000.0,81123000000.0,80872000000.0,84928000000.0,90575000000.0
Total Debt,108040000000.0,111088000000.0,109280000000.0,109615000000.0,111110000000.0
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,73100000000.0,61555000000.0,62482000000.0,55872000000.0,51355000000.0
Other Short Term Investments,32340000000.0,31590000000.0,34074000000.0,31185000000.0,30820000000.0
Cash And Cash Equivalents,40760000000.0,29965000000.0,28408000000.0,24687000000.0,20535000000.0
Cash Equivalents,11218000000.0,1606000000.0,3071000000.0,4637000000.0,2627000000.0
Cash Financial,29542000000.0,28359000000.0,25337000000.0,20050000000.0,17908000000.0

In [39]:
# - cash flow statement
appl.cashflow
appl.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Free Cash Flow,37503000000.0,19435000000.0,24287000000.0,25644000000.0,30218000000.0
Repurchase Of Capital Stock,-20139000000.0,-21003000000.0,-17478000000.0,-19594000000.0,-19475000000.0
Repayment Of Debt,-3984000000.0,0.0,-7500000000.0,5964000000.0,-9615000000.0
Issuance Of Debt,NaN,0.0,NaN,NaN,NaN
Capital Expenditure,-2392000000.0,-2163000000.0,-2093000000.0,-2916000000.0,-3787000000.0
Interest Paid Supplemental Data,NaN,1213000000.0,717000000.0,1170000000.0,703000000.0
Income Tax Paid Supplemental Data,7255000000.0,11659000000.0,2126000000.0,4066000000.0,828000000.0
End Cash Position,41974000000.0,30737000000.0,29898000000.0,27129000000.0,21974000000.0
Beginning Cash Position,30737000000.0,29898000000.0,27129000000.0,21974000000.0,24977000000.0
Changes In Cash,11237000000.0,839000000.0,2769000000.0,5155000000.0,-3003000000.0
Financing Cash Flow,-30585000000.0,-23153000000.0,-24048000000.0,-25724000000.0,-35563000000.0
Cash Flow From Continuing Financing Activities,-30585000000.0,-23153000000.0,-24048000000.0,-25724000000.0,-35563000000.0
Net Other Financing Charges,-2637000000.0,-385000000.0,-2438000000.0,-484000000.0,-2705000000.0
Cash Dividends Paid,-3825000000.0,-3758000000.0,-3849000000.0,-3650000000.0,-3768000000.0
Common Stock Dividend Paid,-3825000000.0,-3758000000.0,-3849000000.0,-3650000000.0,-3768000000.0
Net Common Stock Issuance,-20139000000.0,-21003000000.0,-17478000000.0,-19594000000.0,-19475000000.0
Common Stock Payments,-20139000000.0,-21003000000.0,-17478000000.0,-19594000000.0,-19475000000.0
Net Issuance Payments Of Debt,-3984000000.0,1993000000.0,-283000000.0,-1996000000.0,-9615000000.0
Net Short Term Debt Issuance,-3984000000.0,1993000000.0,1989000000.0,254000000.0,-8214000000.0
Short Term Debt Payments,-3984000000.0,NaN,NaN,NaN,-8214000000.0
Net Long Term Debt Issuance,0.0,0.0,-2272000000.0,-2250000000.0,-1401000000.0
Long Term Debt Payments,0.0,0.0,-7500000000.0,-2250000000.0,-1401000000.0
Long Term Debt Issuance,NaN,0.0,NaN,NaN,NaN
Investing Cash Flow,1927000000.0,2394000000.0,437000000.0,2319000000.0,-1445000000.0
Cash Flow From Continuing Investing Activities,1927000000.0,2394000000.0,437000000.0,2319000000.0,-1445000000.0
Net Other Investing Changes,-284000000.0,-584000000.0,-506000000.0,-106000000.0,-141000000.0
Net Investment Purchase And Sale,4603000000.0,5141000000.0,3036000000.0,5341000000.0,2483000000.0
Sale Of Investment,14383000000.0,13698000000.0,12795000000.0,11385000000.0,7636000000.0
Purchase Of Investment,-9780000000.0,-8557000000.0,-9759000000.0,-6044000000.0,-5153000000.0
Net PPE Purchase And Sale,-2392000000.0,-2163000000.0,-2093000000.0,-2916000000.0,-3787000000.0
Purchase Of PPE,-2392000000.0,-2163000000.0,-2093000000.0,-2916000000.0,-3787000000.0
Operating Cash Flow,39895000000.0,21598000000.0,26380000000.0,28560000000.0,34005000000.0
Cash Flow From Continuing Operating Activities,39895000000.0,21598000000.0,26380000000.0,28560000000.0,34005000000.0
Change In Working Capital,1123000000.0,-6060000000.0,749000000.0,231000000.0,-1497000000.0
Change In Other Working Capital,NaN,NaN,NaN,NaN,131000000.0
Change In Other Current Liabilities,-3865000000.0,45000000.0,1229000000.0,-2132000000.0,3889000000.0
Change In Other Current Assets,-1457000000.0,-821000000.0,-771000000.0,7000000.0,-4099000000.0
Change In Payables And Accrued Expense,-4542000000.0,14901000000.0,3974000000.0,-14689000000.0,-6075000000.0
Change In Payable,-4542000000.0,14901000000.0,3974000000.0,-14689000000.0,-6075000000.0
Change In Account Payable,-4542000000.0,14901000000.0,3974000000.0,-14689000000.0,-6075000000.0
Change In Inventory,-137000000.0,952000000.0,-22000000.0,-741000000.0,-1807000000.0
Change In Receivables,11124000000.0,-21137000000.0,-3661000000.0,17786000000.0,6595000000.0
Changes In Account Receivables,6555000000.0,-9297000000.0,-1987000000.0,5321000000.0,4275000000.0
Other Non Cash Items,-989000000.0,-576000000.0,81000000.0,-1415000000.0,-317000000.0
Stock Based Compensation,2997000000.0,2625000000.0,2617000000.0,2686000000.0,2905000000.0
Depreciation Amortization Depletion,2848000000.0,2653000000.0,3052000000.0,2898000000.0,2916000000.0
Depreciation And Amortization,2848000000.0,2653000000.0,3052000000.0,2898000000.0,2916000000.0
Net Income From Continuing Operations,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0

In [78]:
appl.get_income_stmt()

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
TaxEffectOfUnusualItems,0.0,0.0,0.0,0.0
TaxRateForCalcs,0.147,0.162,0.133,0.144
NormalizedEBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,96995000000.0,99803000000.0,94680000000.0,57411000000.0
ReconciledDepreciation,11519000000.0,11104000000.0,11284000000.0,11056000000.0
ReconciledCostOfRevenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
EBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
EBIT,117669000000.0,122034000000.0,111852000000.0,69964000000.0
NetInterestIncome,-183000000.0,-106000000.0,198000000.0,890000000.0
InterestExpense,3933000000.0,2931000000.0,2645000000.0,2873000000.0
InterestIncome,3750000000.0,2825000000.0,2843000000.0,3763000000.0
NormalizedIncome,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeFromContinuingAndDiscontinuedOperation,96995000000.0,99803000000.0,94680000000.0,57411000000.0
TotalExpenses,268984000000.0,274891000000.0,256868000000.0,208227000000.0
TotalOperatingIncomeAsReported,114301000000.0,119437000000.0,108949000000.0,66288000000.0
DilutedAverageShares,15812547000.0,16325819000.0,16864919000.0,17528214000.0
BasicAverageShares,15744231000.0,16215963000.0,16701272000.0,17352119000.0
DilutedEPS,6.13,6.11,5.61,3.28
BasicEPS,6.16,6.15,5.67,3.31
DilutedNIAvailtoComStockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeCommonStockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncome,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeIncludingNoncontrollingInterests,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeContinuousOperations,96995000000.0,99803000000.0,94680000000.0,57411000000.0
TaxProvision,16741000000.0,19300000000.0,14527000000.0,9680000000.0
PretaxIncome,113736000000.0,119103000000.0,109207000000.0,67091000000.0
OtherIncomeExpense,-382000000.0,-228000000.0,60000000.0,-87000000.0
OtherNonOperatingIncomeExpenses,-382000000.0,-228000000.0,60000000.0,-87000000.0
NetNonOperatingInterestIncomeExpense,-183000000.0,-106000000.0,198000000.0,890000000.0
InterestExpenseNonOperating,3933000000.0,2931000000.0,2645000000.0,2873000000.0
InterestIncomeNonOperating,3750000000.0,2825000000.0,2843000000.0,3763000000.0
OperatingIncome,114301000000.0,119437000000.0,108949000000.0,66288000000.0
OperatingExpense,54847000000.0,51345000000.0,43887000000.0,38668000000.0
ResearchAndDevelopment,29915000000.0,26251000000.0,21914000000.0,18752000000.0
SellingGeneralAndAdministration,24932000000.0,25094000000.0,21973000000.0,19916000000.0
GrossProfit,169148000000.0,170782000000.0,152836000000.0,104956000000.0
CostOfRevenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
TotalRevenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0
OperatingRevenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0

In [79]:
# show holders
appl.major_holders
appl.institutional_holders
appl.mutualfund_holders
appl.insider_transactions
appl.insider_purchases
appl.insider_roster_holders

,Name,Position,URL,Most Recent Transaction,Latest Transaction Date,Shares Owned Indirectly,Position Indirect Date,Shares Owned Directly,Position Direct Date
0,ADAMS KATHERINE L,General Counsel,,Sale,2023-11-17,293266.0,1.700179e+09,NaN,NaT
1,BELL JAMES A,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,38527.0,2024-02-01
2,GORE ALBERT A JR,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,468995.0,2024-02-01
3,GORSKY ALEX,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,4023.0,2024-02-01
4,JUNG ANDREA,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,74489.0,2024-02-01
5,KONDO CHRISTOPHER,Officer,,Sale,2023-11-29,NaN,NaN,29174.0,2023-11-29
6,LEVINSON ARTHUR D,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,4590580.0,2024-02-01
7,LOZANO MONICA C.,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,7091.0,2024-02-01
8,SUGAR RONALD D,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,107795.0,2024-02-01
9,WAGNER SUSAN L,Director,,Conversion of Exercise of derivative security,2024-02-01,NaN,NaN,67375.0,2024-02-01

In [42]:
# show recommendations
appl.recommendations
appl.recommendations_summary
appl.upgrades_downgrades

                                  Firm      ToGrade    FromGrade Action
GradeDate
2024-02-02 20:29:37          JP Morgan   Overweight   Overweight   main
2024-02-02 18:02:06        Oppenheimer   Outperform   Outperform   reit
2024-02-02 13:49:30            Wedbush   Outperform   Outperform   reit
2024-02-02 12:44:37           Barclays  Underweight  Underweight   main
2024-02-02 12:14:28            Needham          Buy          Buy   reit
...                                ...          ...          ...    ...
2012-03-14 12:21:00  Canaccord Genuity          Buy                main
2012-03-14 10:13:00     Morgan Stanley   Overweight                main
2012-03-13 10:08:00          Jefferies          Buy                main
2012-03-08 12:33:00     FBN Securities   Outperform                main
2012-02-09 13:17:00  Canaccord Genuity          Buy                main

[1022 rows x 4 columns]

In [43]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
appl.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-01-30 16:00:00-05:00           NaN           NaN          NaN
2024-10-31 06:00:00-04:00           NaN           NaN          NaN
2024-08-01 06:00:00-04:00           NaN           NaN          NaN
2024-05-02 06:00:00-04:00          1.51           NaN          NaN
2024-02-01 16:00:00-05:00          2.10          2.18       0.0396
2024-01-31 05:00:00-05:00          2.10          2.18       0.0381
2023-11-02 16:00:00-04:00          1.39          1.46       0.0492
2023-08-03 16:00:00-04:00          1.19          1.26       0.0549
2023-05-04 16:00:00-04:00          1.43          1.52       0.0603
2023-02-02 16:00:00-05:00          1.94          1.88      -0.0288
2022-10-27 16:00:00-04:00          1.27          1.29       0.0155
2022-07-28 16:00:00-04:00          1.16          1.20       0.0325

In [44]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
appl.isin

'US0378331005'

In [45]:
# show options expirations
appl.options

('2024-02-09',
 '2024-02-16',
 '2024-02-23',
 '2024-03-01',
 '2024-03-08',
 '2024-03-15',
 '2024-03-22',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-07-19',
 '2024-08-16',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-03-21',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16',
 '2026-06-18')

In [46]:
# show news
appl.news

[{'uuid': '00085c3f-724a-39ca-aa21-d383d5c5ef58',
  'title': 'Here are my favorite Vision Pro apps (so far)',
  'publisher': 'TechCrunch',
  'link': 'https://finance.yahoo.com/m/00085c3f-724a-39ca-aa21-d383d5c5ef58/here-are-my-favorite-vision.html',
  'providerPublishTime': 1707436280,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/jvOMriS3vWCqZxjZJlY.EA--~B/aD0xMzUwO3c9MjQwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_for_finance_733/fd373aec835359acf5c935e81122a73a',
     'width': 2400,
     'height': 1350,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/V3a18BNf0FCGTZBB3apaYA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/techcrunch_for_finance_733/fd373aec835359acf5c935e81122a73a',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL']},
 {'uuid': '0c2b9bd6-ab6a-3af7-8d2f-2ce2dce0abe4',
  'title': '30 Largest Companies in the World by Revenue',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/30-largest-companies-world-revenue-230959905.html',
  'providerPublishTime': 1707433799,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/bugMxaCL2C1BTh19SMyHBA--~B/aD04MTY7dz0xNDU2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/a60d9d9ecc45e68859f24af1edf78365',
     'width': 1456,
     'height': 816,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/IM2.nhx7Xky.c8VdxFjZCg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/a60d9d9ecc45e68859f24af1edf78365',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL',
   '^GSPC',
   'WMT',
   'AMZN',
   'CVX',
   'STLAM.MI',
   'MCK',
   'CI',
   'CAH',
   'BP',
   'MSFT',
   'GOOG',
   'TM',
   'SSNLF',
   'XOM',
   'COST']},
 {'uuid': '1999f47d-d143-30b4-bb04-5aaf43028d51',
  'title': '15 Most Respected Countries in Asia',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/15-most-respected-countries-asia-224213258.html',
  'providerPublishTime': 1707432133,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/dn1vp31vA28z8acSyMl9.w--~B/aD0xMjgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/insidermonkey.com/0b1fe5bbe3920038f0ecbda6e56fe018',
     'width': 1920,
     'height': 1280,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/t_O_yR6vfO3JWLEPcFiPAg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/0b1fe5bbe3920038f0ecbda6e56fe018',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL', 'AMZN']},
 {'uuid': '6f25e2f5-30e0-3f2e-9643-45c3c44db90d',
  'title': 'Why did Tim Cook’s pay package hold up in court while Elon’s failed?',
  'publisher': 'Fortune',
  'link': 'https://finance.yahoo.com/news/why-did-tim-cook-pay-222112357.html',
  'providerPublishTime': 1707430872,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Z8EJjZTq8njQf15AXLWbpA--~B/aD0xNDg4O3c9MjA0ODthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/fortune_175/2851644d255bd563f238ce5e06001111',
     'width': 2048,
     'height': 1488,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/REav6oWLuvaT4aYEXqyMjA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/fortune_175/2851644d255bd563f238ce5e06001111',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL', 'TSLA']},
 {'uuid': 'dd686f86-c7e9-3e0d-b46d-084322bbadba',
  'title': 'Alphabet’s Gemini AI rollout reveals the battle lines of the coming chatbot wars',
  'publisher': 'Fortune',
  'link': 'https://finance.yahoo.com/news/alphabet-gemini-ai-rollout-reveals-221412589.html',
  'providerPublishTime': 1707430452,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/62HpZs718AjYlJceT8Y3XQ--~B/aD0xNDMwO3c9MjA0ODthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/fortune_175/b7ce9b0d715d5c13883b3366ef2e83ae',
     'width': 2048,
     'height': 1430,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/NROpK7TNYuAyg0ojUjsEnA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/fortune_175/b7ce9b0d715d5c13883b3366ef2e83ae',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOG', 'MSFT', 'AAPL']},
 {'uuid': 'fc9ce78d-bbad-33da-8853-70175d555a0f',
  'title': 'Key House Republican Presses Biden to Classify TikTok as Foreign Agent',
  'publisher': 'Bloomberg',
  'link': 'https://finance.yahoo.com/news/key-house-republican-presses-biden-202924532.html',
  'providerPublishTime': 1707424164,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/kZ91i0D558TnvyVk7rumtg--~B/aD0xMzMzO3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/bloomberg_markets_842/e55318b4842fabc6bbd92f19975e7208',
     'width': 2000,
     'height': 1333,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/owBUML1_4YiDYL91SWOs8g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_markets_842/e55318b4842fabc6bbd92f19975e7208',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL']},
 {'uuid': '64d5ffd0-a5ad-3b10-9f96-2a3000636421',
  'title': "Steve Jobs Didn't Think He Needed To Shower Because He Only Ate Fruit — But His Body Odor Had Him Banished To The Night Shift When Colleagues Complained About The Smell",
  'publisher': 'Benzinga',
  'link': 'https://finance.yahoo.com/news/steve-jobs-didnt-think-needed-171754585.html',
  'providerPublishTime': 1707412674,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/n9yNNgKHgJ8qEp3BxCYjxA--~B/aD01NzY7dz0xMDI0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/bb36887d9af5f8d2f3efae62e55b02d0',
     'width': 1024,
     'height': 576,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/OL_88Oyk2hM4Kn8xIlZdEg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/bb36887d9af5f8d2f3efae62e55b02d0',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL']},
 {'uuid': '1da1f354-003c-3f12-9b76-e318bade6513',
  'title': "Apple's Holiday Quarter Broke Years-Long Streak Of Revenue Declines But China Slowdown Overshadowed Even Its Record Service Revenue",
  'publisher': 'Benzinga',
  'link': 'https://finance.yahoo.com/news/apples-holiday-quarter-broke-years-165949588.html',
  'providerPublishTime': 1707411589,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/xbuFGsAvcXLag5LjTMxoiA--~B/aD02NzU7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/0583c4d8ad8b9fa64e2502e1f99b2259',
     'width': 1200,
     'height': 675,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/vyM9xVFuob1sdet3SZTpCA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/0583c4d8ad8b9fa64e2502e1f99b2259',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL', 'MSFT']}]

In [48]:
# get option chain for specific expiration
opt = appl.option_chain('2024-02-23')
opt.calls
# data available via: opt.calls, opt.puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL240223C00100000,2024-01-30 15:44:16+00:00,100.0,89.33,87.95,88.55,0.000000,0.000000,NaN,1,1.456057,True,REGULAR,USD
1,AAPL240223C00110000,2024-01-22 17:07:40+00:00,110.0,83.50,78.00,78.55,0.000000,0.000000,NaN,1,1.257816,True,REGULAR,USD
2,AAPL240223C00120000,2024-01-22 14:56:30+00:00,120.0,75.00,68.00,68.85,0.000000,0.000000,1.0,1,0.962891,True,REGULAR,USD
3,AAPL240223C00130000,2024-01-29 20:16:12+00:00,130.0,62.10,58.05,58.60,0.000000,0.000000,1.0,31,0.593754,True,REGULAR,USD
4,AAPL240223C00140000,2024-01-19 14:58:50+00:00,140.0,50.00,48.10,48.65,0.000000,0.000000,2.0,3,0.609379,True,REGULAR,USD
5,AAPL240223C00145000,2024-02-08 20:41:42+00:00,145.0,43.32,43.10,43.70,-0.099998,-0.230305,1.0,2,0.572270,True,REGULAR,USD
6,AAPL240223C00150000,2024-02-05 15:24:30+00:00,150.0,37.00,38.15,38.70,0.000000,0.000000,2.0,28,0.525395,True,REGULAR,USD
7,AAPL240223C00155000,2024-02-07 19:50:19+00:00,155.0,34.50,33.15,33.75,0.000000,0.000000,1.0,22,0.585942,True,REGULAR,USD
8,AAPL240223C00160000,2024-02-08 20:24:59+00:00,160.0,28.52,28.25,28.75,-1.029999,-3.485614,16.0,96,0.507329,True,REGULAR,USD
9,AAPL240223C00165000,2024-02-07 20:18:00+00:00,165.0,24.45,23.25,23.80,0.000000,0.000000,2.0,76,0.439947,True,REGULAR,USD
10,AAPL240223C00170000,2024-02-08 17:54:34+00:00,170.0,18.40,18.30,18.75,-0.980000,-5.056757,36.0,192,0.351081,True,REGULAR,USD
11,AAPL240223C00175000,2024-02-08 20:54:40+00:00,175.0,13.57,13.50,13.80,-1.030001,-7.054799,11.0,135,0.280281,True,REGULAR,USD
12,AAPL240223C00180000,2024-02-08 20:56:15+00:00,180.0,8.95,8.85,9.00,-1.050000,-10.500002,293.0,947,0.221443,True,REGULAR,USD
13,AAPL240223C00185000,2024-02-08 20:54:40+00:00,185.0,4.80,4.75,4.90,-0.950000,-16.521736,644.0,4128,0.195198,True,REGULAR,USD
14,AAPL240223C00190000,2024-02-08 20:59:54+00:00,190.0,2.02,2.00,2.05,-0.650000,-24.344572,5016.0,8817,0.183724,False,REGULAR,USD
15,AAPL240223C00195000,2024-02-08 20:59:54+00:00,195.0,0.69,0.67,0.71,-0.260000,-27.368420,4745.0,7124,0.187508,False,REGULAR,USD
16,AAPL240223C00200000,2024-02-08 20:56:06+00:00,200.0,0.23,0.23,0.24,-0.110000,-32.352940,2974.0,17056,0.200203,False,REGULAR,USD
17,AAPL240223C00205000,2024-02-08 20:55:36+00:00,205.0,0.09,0.09,0.10,-0.030000,-24.999996,418.0,10980,0.221687,False,REGULAR,USD
18,AAPL240223C00210000,2024-02-08 20:56:08+00:00,210.0,0.04,0.04,0.05,-0.020000,-33.333336,122.0,13703,0.246101,False,REGULAR,USD
19,AAPL240223C00215000,2024-02-08 20:34:35+00:00,215.0,0.02,0.01,0.03,-0.010000,-33.333336,42.0,4790,0.271492,False,REGULAR,USD
20,AAPL240223C00220000,2024-02-08 20:07:42+00:00,220.0,0.01,0.00,0.02,-0.010000,-50.000000,129.0,5879,0.298835,False,REGULAR,USD
21,AAPL240223C00225000,2024-02-08 15:25:27+00:00,225.0,0.01,0.00,0.02,0.000000,0.000000,1.0,362,0.335944,False,REGULAR,USD
22,AAPL240223C00230000,2024-02-06 15:41:33+00:00,230.0,0.01,0.00,0.04,0.000000,0.000000,200.0,789,0.402350,False,REGULAR,USD
23,AAPL240223C00235000,2024-02-05 19:50:38+00:00,235.0,0.01,0.00,0.02,0.000000,0.000000,192.0,229,0.406256,False,REGULAR,USD
24,AAPL240223C00240000,2024-02-01 18:00:43+00:00,240.0,0.02,0.00,0.01,0.000000,0.000000,5.0,123,0.414068,False,REGULAR,USD
25,AAPL240223C00245000,2024-01-29 16:23:36+00:00,245.0,0.01,0.00,0.02,0.000000,0.000000,1.0,1,0.476568,False,REGULAR,USD
26,AAPL240223C00250000,2024-02-05 16:51:30+00:00,250.0,0.01,0.00,0.02,0.000000,0.000000,5.0,6,0.507817,False,REGULAR,USD
27,AAPL240223C00255000,2024-02-06 14:30:05+00:00,255.0,0.01,0.00,0.01,0.000000,0.000000,5.0,8,0.507817,False,REGULAR,USD
28,AAPL240223C00260000,2024-01-30 15:01:08+00:00,260.0,0.01,0.00,0.01,0.000000,0.000000,NaN,1,0.500005,False,REGULAR,USD
29,AAPL240223C00265000,2024-02-05 14:30:01+00:00,265.0,0.01,0.00,0.01,0.000000,0.000000,5.0,86,0.531255,False,REGULAR,USD

In [57]:
temp = yf.download('APPL')
temp

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['APPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 1925-03-04 -> 2024-02-08)')

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [62]:
import yfinance as yf
data = yf.download("AAPL GOOG MSFT", period="1mo")
data

[*********************100%%**********************]  3 of 3 completed

Price        Adj Close                               Close              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG
Date
2024-01-09  185.139999  142.559998  375.790009  185.139999  142.559998
2024-01-10  186.190002  143.800003  382.769989  186.190002  143.800003
2024-01-11  185.589996  143.669998  384.630005  185.589996  143.669998
2024-01-12  185.919998  144.240005  388.470001  185.919998  144.240005
2024-01-16  183.630005  144.080002  390.269989  183.630005  144.080002
2024-01-17  182.679993  142.889999  389.470001  182.679993  142.889999
2024-01-18  188.630005  144.990005  393.869995  188.630005  144.990005
2024-01-19  191.559998  147.970001  398.670013  191.559998  147.970001
2024-01-22  193.889999  147.710007  396.510010  193.889999  147.710007
2024-01-23  195.179993  148.679993  398.899994  195.179993  148.679993
2024-01-24  194.500000  150.350006  402.559998  194.500000  150.350006
2024-01-25  194.169998  153.639999  404.869995  194.169998  153.639999
2024-01-26  192.419998  153.789993  403.929993  192.419998  153.789993
2024-01-29  191.729996  154.839996  409.720001  191.729996  154.839996
2024-01-30  188.039993  153.050003  408.589996  188.039993  153.050003
2024-01-31  184.399994  141.800003  397.579987  184.399994  141.800003
2024-02-01  186.860001  142.710007  403.779999  186.860001  142.710007
2024-02-02  185.850006  143.539993  411.220001  185.850006  143.539993
2024-02-05  187.679993  144.929993  405.649994  187.679993  144.929993
2024-02-06  189.300003  145.410004  405.489990  189.300003  145.410004
2024-02-07  189.410004  146.679993  414.049988  189.410004  146.679993
2024-02-08  188.320007  147.220001  414.109985  188.320007  147.220001

Price                         High                                 Low  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL
Date
2024-01-09  375.790009  185.149994  142.800003  375.989990  182.729996
2024-01-10  382.769989  186.399994  144.524994  384.170013  183.919998
2024-01-11  384.630005  187.050003  146.660004  390.679993  183.619995
2024-01-12  388.470001  186.740005  144.740005  388.679993  185.190002
2024-01-16  390.269989  184.259995  145.839996  394.029999  180.929993
2024-01-17  389.470001  182.929993  143.410004  390.109985  180.300003
2024-01-18  393.869995  189.139999  145.585007  393.989990  185.830002
2024-01-19  398.670013  191.949997  148.039993  398.670013  188.820007
2024-01-22  396.510010  195.330002  150.014999  400.619995  192.259995
2024-01-23  398.899994  195.750000  148.860001  399.380005  193.830002
2024-01-24  402.559998  196.380005  151.570007  405.630005  194.339996
2024-01-25  404.869995  196.270004  154.759995  407.010010  193.110001
2024-01-26  403.929993  194.759995  154.110001  406.170013  191.940002
2024-01-29  409.720001  192.199997  155.199997  409.980011  189.580002
2024-01-30  408.589996  191.800003  155.039993  413.049988  187.470001
2024-01-31  397.579987  187.100006  145.589996  415.320007  184.350006
2024-02-01  403.779999  186.949997  144.619995  408.000000  183.820007
2024-02-02  411.220001  187.330002  143.880005  412.649994  179.250000
2024-02-05  405.649994  189.250000  146.669998  411.160004  185.839996
2024-02-06  405.489990  189.309998  146.740005  407.970001  186.770004
2024-02-07  414.049988  191.050003  147.000000  414.299988  188.610001
2024-02-08  414.109985  189.539993  147.610001  415.559998  187.350006

Price                                     Open                          \
Ticker            GOOG        MSFT        AAPL        GOOG        MSFT
Date
2024-01-09  139.789993  371.190002  183.919998  140.059998  372.010010
2024-01-10  142.460007  376.320007  184.350006  142.520004  376.369995
2024-01-11  142.214996  380.380005  186.539993  144.895004  386.000000
2024-01-12  143.360001  384.649994  186.059998  144.339996  385.489990
2024-01-16  143.056000  387.619995  182.160004  143.429993  393.660004
2024-01-17  140.509995  384.809998  181.270004  142.910004  387.980011
2024-01-18  143.350006  390.119995  186.089996  143.440002  391.720001
2024-01-19  145.800003  393.500000  189.330002  146.304993  395.760010
2024-01-22  147.580002  393.589996  192.300003  148.710007  400.019989
2024-01-23  147.190002  393.929993  195.020004  147.720001  395.750000
2024-01-24  149.839996  400.450012  195.419998  150.289993  401.540009
2024-01-25  151.220001  402.529999  195.220001  151.740005  404.320007
2024-01-26  152.800003  402.429993  194.270004  152.869995  404.369995
2024-01-29  152.919998  404.329987  192.009995  153.639999  406.059998
2024-01-30  152.774994  406.450012  190.940002  154.009995  412.260010
2024-01-31  141.550003  397.209991  187.039993  145.389999  406.959991
2024-02-01  142.259995  401.799988  183.990005  143.690002  401.829987
2024-02-02  138.169998  403.559998  179.860001  140.889999  403.809998
2024-02-05  143.910004  403.989990  188.149994  144.039993  409.899994
2024-02-06  144.520004  402.910004  186.860001  145.960007  405.880005
2024-02-07  145.210007  407.399994  190.639999  146.119995  407.440002
2024-02-08  146.419998  412.529999  189.389999  146.970001  414.049988

Price          Volume
Ticker           AAPL      GOOG      MSFT
Date
2024-01-09   42841800  19579700  20830000
2024-01-10   46792900  16641900  25514200
2024-01-11   49128400  17471100  27850800
2024-01-12   40444700  13995200  21645700
2024-01-16   65603000  19198900  27202300
2024-01-17   47317400  17884500  22234100
2024-01-18   78005800  18876800  23392100
2024-01-19   68741000  27170900  29272000
2024-01-22   60133900  21829200  27016900
2024-01-23   42355600  14113600  20525900
2024-01-24   53631300  19245000  24867000
2024-01-25   54822100  21495100  21021200
2024-01-26   44594000  19494500  17803300
2024-01-29   47145600  20909300  24510200
2024-01-30   55859400  26578900  33477600
2024-01-31   55467800  43908600  47871100
2024-02-01   64885400  25526900  30657700
2024-02-02  102518000  42116900  28245000
2024-02-05   69668800  29254400  25352300
2024-02-06   43490800  21517700  18382600
2024-02-07   53439000  21436100  22340500
2024-02-08   40928600  18219900  21208600

In [63]:
import yfinance as yf
yf.set_tz_cache_location("custom/cache/location")